In [1]:
%pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

df2 = pd.read_csv('messy_employees.csv')

In [3]:
df2['age']

0      33.0
1      32.0
2      24.0
3      27.0
4      30.0
       ...
213    30.0
214    37.0
215    30.0
216    44.0
217    47.0
Name: age, Length: 218, dtype: float64

In [5]:
df2[['name','age']]

                name   age
0       Rohan Tanaka  33.0
1      Vikram Chen    32.0
2        Arjun Ali    24.0
3        Arjun Jones  27.0
4        Hassan Wong  30.0
..               ...   ...
213       Liam Brown  30.0
214        Wei Brown  37.0
215      Aarav Jones  30.0
216        Aarav Ali  44.0
217         Wei Nair  47.0

[218 rows x 2 columns]

In [7]:
## A list in the brackets always gives back a table.
df2[['age']]

      age
0    33.0
1    32.0
2    24.0
3    27.0
4    30.0
..    ...
213  30.0
214  37.0
215  30.0
216  44.0
217  47.0

[218 rows x 1 columns]

In [10]:
(df2['age'] > 40).value_counts(dropna = False)

age
False    185
True      33
Name: count, dtype: int64

In [11]:
## it will print the whole content where the conditions will be true
df2[(df2['age'] > 40)]

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,exit_date
19,E1109,Emma Garcia,47.0,HR,Bangalore,03/04/2019,21,NaN,3971.19,2.7,34.0,3,No,emma.garcia@corp.com,NaN
27,E1163,Fatima Ali,41.0,SALES,Singapore,2022-01-14,19,146843.57,5364.19,3.2,45.1,5,No,fatima.ali@corp.com,NaN
30,E1055,Olivia Singh,48.0,Engineering,melbourne,2022-12-25,22,NaN,8268.73,NaN,39.8,3,Yes,olivia.singh@corp.com,NaN
37,E1057,Sophia Tanaka,41.0,Finance,NaN,2017-03-12,15,142867.92,4523.35,2.7,41.0,5,N,sophia.tanaka@corp.com,NaN
46,E1066,Aarav Ali,44.0,Support,Singapore,2023-04-10,18,111980.12,NaN,3.2,39.6,4,1,aarav.ali@corp.com,NaN
57,E1013,Liam Jones,43.0,Finance,PERTH,2017-11-26,17,"$148,093.29",7274.97,3.4,38.4,5,No,liam.jones@corp.com,NaN
58,E1129,Hassan Ali,44.0,Support,Singapore,2017-01-04,17,84377.36,5889.08,5.0,34.8,4,Yes,hassan.ali@corp.com,NaN
59,E1173,Liam Nair,45.0,Marketing,Brisbane,2013/05/17,24,NaN,4321.40,2.5,37.5,3,Yes,liam.nair@corp.com,NaN
61,E1028,Ananya Jones,45.0,HR,Bangalore,2023-02-09,19,115385.81,5816.75,3.6,42.3,2,0,ananya.jones@corp.com,NaN
63,E1076,Sneha Wong,52.0,Finance,Sydney,2023-05-23,29,173289.47,5001.23,3.3,37.6,1,Yes,sneha.wong@corp.com,NaN
74,E1199,Sneha Tanaka,42.0,HR,Bangalore,2020-06-16,15,NaN,2960.25,NaN,NaN,2,TRUE,sneha.tanaka@corp.com,NaN
76,E1146,Noah Nair,49.0,Sales,Sydney,2018-07-26,24,161826.64,6754.46,3.6,39.4,3,FALSE,noah.nair@corp.com,NaN
79,E1160,Karan Ali,41.0,Marketing,Perth,2013-03-28,13,119699.16,4778.03,2.8,41.6,6,Yes,karan.ali@corp.com,NaN
95,E1064,Fatima Kumar,48.0,Finance,PERTH,2023-06-17,23,142378.07,4031.58,2.7,40.4,5,No,fatima.kumar@corp.com,NaN
101,E1081,Wei Nair,45.0,support,Bangalore,10/10/2014,16,"$115,697.65",5881.23,3.4,40.9,4,No,wei.nair@corp.com,NaN
102,E1007,Priya Chen,45.0,SALES,Brisbane,2020/04/19,18,126866.88,7075.12,3.7,39.0,4,No,priya.chen@corp.com,NaN
111,E1079,Fatima Chen,150.0,Finance,Bangalore,2024-08-07,2,91209.98,NaN,4.1,38.8,2,Yes,fatima.chen@corp.com,NaN
124,E1090,Olivia Singh,49.0,Engineering,singapore,03-Jul-2019,25,"$190,992.36",8402.67,4.2,42.2,4,No,olivia.singh@corp.com,NaN
125,E1199,Sneha Tanaka,42.0,HR,Bangalore,2020-06-16,15,101090.15,2960.25,3.5,NaN,2,TRUE,sneha.tanaka@corp.com,NaN
131,E1053,Aarav Sharma,150.0,Marketing,Perth,2023-10-12,4,77513.97,3032.57,2.9,28.7,4,Y,aarav.sharma@corp.com,NaN
136,E1076,Sneha Wong,52.0,Finance,Sydney,2023-05-23,29,173289.47,5001.23,3.3,37.6,1,Yes,sneha.wong@corp.com,NaN
139,E1170,Yuki Nair,43.0,HR,Brisbane,2017-10-21,14,101684.57,3528.31,2.3,38.3,6,No,,NaN
146,E1064,Fatima Kumar,48.0,Finance,PERTH,2023-06-17,23,NaN,4031.58,NaN,40.4,5,No,fatima.kumar@corp.com,NaN
148,E1198,Meera Jones,49.0,Sales,brisbane,2011-05-24,24,"$142,344.14",NaN,3.1,47.3,5,No,meera.jones@corp.com,NaN
152,E1033,Arjun Reddy,51.0,Engineering,Melbourne,09-Mar-2013,26,171186.2,6439.54,2.5,39.1,7,No,arjun.reddy@corp.com,NaN
159,E1100,Rohan Reddy,41.0,Engineering,Perth,11/12/2023,17,"153,942.53 AUD",6889.69,3.7,38.5,2,Yes,rohan.reddy@corp.com,NaN
170,E1093,Wei Patel,150.0,Engineering,Melbourne,2018-08-14,11,NaN,7459.77,3.4,30.1,4,FALSE,wei.patel@corp.com,2024-06-30
172,E1118,Liam Chen,44.0,Mktg,Melbourne,-,24,145057.18,4168.20,3.2,NaN,2,1,liam.chen@corp.com,NaN
190,E1188,Noah Reddy,41.0,Sales,Bangalore,2019-03-05,21,134533.2,NaN,3.5,43.2,7,FALSE,noah.reddy@corp.com,NaN
193,E1055,Olivia Singh,48.0,Engineering,melbourne,2022-12-25,22,NaN,8268.73,3.6,39.8,3,Yes,olivia.singh@corp.com,NaN
206,E1072,Wei Khan,999.0,Finance,NaN,2020-02-06,0,"$84,192.92",3085.45,2.8,42.8,5,Yes,wei.khan@corp.com,NaN
216,E1196,Aarav Ali,44.0,Marketing,Singapore,-,24,153627.16,10278.26,4.2,35.9,4,Yes,aarav.ali@corp.com,NaN
217,E1175,Wei Nair,47.0,?,Brisbane,2023-10-24,26,138346.24,5404.73,3.3,0.0,2,No,wei.nair@corp.com,NaN

In [14]:
df2[df2["department"] == "hr"]
df2[df2["salary"].isna()]
df2[df2["department"] != "hr"]

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,exit_date
0,E1139,Rohan Tanaka,33.0,Sales,NaN,06/02/2021,8,96558.7,2723.68,2.9,40.0,2,1,rohan.tanaka@corp.com,NaN
1,E1065,Vikram Chen,32.0,Finance,Melbourne,2021-12-24,5,95487.76,1812.91,2.1,49.2,3,N,vikram.chen@corp.com,NaN
2,E1095,Arjun Ali,24.0,sales,PERTH,2014-05-14,0,NaN,882.69,1.6,36.8,3,No,,NaN
3,E1022,Arjun Jones,27.0,support,Singapore,2023-06-09,0,67002.04,2877.76,3.4,45.7,2,Yes,arjun.jones@corp.com,NaN
4,E1063,Hassan Wong,30.0,Human Resources,Singapore,2011-07-22,0,63310.87,1661.07,2.8,37.0,4,Yes,hassan.wong@corp.com,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,E1016,Liam Brown,30.0,HR,Brisbane,2024-11-25,4,72999.99,2982.06,4.3,37.2,3,Yes,liam.brown@corp.com,NaN
214,E1067,Wei Brown,37.0,Sales,PERTH,27-Mar-2016,14,106776.08,4680.69,3.2,41.3,3,Yes,wei.brown@corp.com,NaN
215,E1025,Aarav Jones,30.0,Marketing,NaN,03/05/2020,4,91492.85,3048.72,3.7,47.6,9,1,aarav.jones@corp.com,NaN
216,E1196,Aarav Ali,44.0,Marketing,Singapore,-,24,153627.16,10278.26,4.2,35.9,4,Yes,aarav.ali@corp.com,NaN
217,E1175,Wei Nair,47.0,?,Brisbane,2023-10-24,26,138346.24,5404.73,3.3,0.0,2,No,wei.nair@corp.com,NaN

In [15]:
## it means at the age columns , make all those values none whose age is above than 75
df2.loc[(df2['age'] > 75),"age"] = None

In [16]:
(df2["age"] > 75).sum()

np.int64(0)

In [17]:
df2["department"].value_counts()

department
HR                  27
Engineering         26
Finance             26
Sales               23
Support             20
Marketing           18
?                   16
Mktg                11
support              7
SALES                6
hr                   6
FINANCE              5
sales                5
marketing            5
Human Resources      4
H.R.                 4
Engg                 2
finance              2
engineering          2
Customer Support     1
ENGINEERING          1
Sales                1
Name: count, dtype: int64

In [18]:
df2["department"] = df2["department"].str.strip().str.lower()

In [19]:
df2["department"].value_counts()

department
sales               35
finance             33
hr                  33
engineering         29
support             27
marketing           23
?                   16
mktg                11
human resources      4
h.r.                 4
engg                 2
customer support     1
Name: count, dtype: int64

In [20]:
df2["department"] = df2["department"].replace(
    {
        "h.r." : "hr",
        "?" : None,
        "human resources" : "hr",
        "mktg" : "marketing ",
        "engg" : "engineering"
    }
)

In [21]:
df2["department"].value_counts()

department
hr                  41
sales               35
finance             33
engineering         31
support             27
marketing           23
marketing           11
customer support     1
Name: count, dtype: int64

In [22]:
df2["department"] = df2["department"].replace({"marketing " : "marketing"})

In [24]:
df2["department"].value_counts(dropna = False)

department
hr                  41
sales               35
marketing           34
finance             33
engineering         31
support             27
None                16
customer support     1
Name: count, dtype: int64

In [26]:
df2["salary"].value_counts(dropna = False)

salary
NaN           28
85829.66       2
78722.66       2
$84,392.96     2
$64,862.90     2
              ..
64238.05       1
161826.64      1
65626.59       1
119699.16      1
138346.24      1
Name: count, Length: 178, dtype: int64

In [27]:
df2["salary"] = df2["salary"].replace("$","",regex = True)
df2["salary"] = df2["salary"].replace(",","",regex = True)
df2["salary"] = df2["salary"].replace(" ","",regex = True)

In [29]:
df2["salary"] = pd.to_numeric(df2["salary"] , errors= "coerce")

In [31]:
df2["salary"].value_counts(dropna = False)

salary
NaN          63
122829.74     2
99920.31      2
173289.47     2
85829.66      2
             ..
92647.44      1
103382.53     1
115385.81     1
84377.36      1
138346.24     1
Name: count, Length: 145, dtype: int64

In [32]:
df2["salary"].describe()

count    1.550000e+02
mean     1.561213e+05
std      7.964329e+05
min     -4.500000e+04
25%      7.351244e+04
50%      8.850674e+04
75%      1.086638e+05
max      9.999999e+06
Name: salary, dtype: float64

In [33]:
df2["remote"].value_counts(dropna = False)

remote
Yes      72
No       71
1        13
no       12
0        11
Y        11
TRUE     10
FALSE     9
N         6
yes       3
Name: count, dtype: int64

In [34]:
df2["remote"] = df2["remote"].map({
    "Yes" : True,
    "No" : False,
    "1":True,
    "Y":True,
    "yes":True,
    "TRUE" : True,
    "no" : False,
    "0" : False,
    "False" : False,
    "N" : False
})

In [35]:
df2["remote"].value_counts(dropna = False)

remote
True     109
False    100
NaN        9
Name: count, dtype: int64

In [38]:
df2["date_of_joining"] = pd.to_datetime(df2["date_of_joining"] , dayfirst = True , format = "mixed" , errors = "coerce")

In [41]:
df2["date_of_joining"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 218 entries, 0 to 217
Series name: date_of_joining
Non-Null Count  Dtype
--------------  -----
208 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.8 KB

In [42]:
df2["tenure_years"] = (pd.Timestamp("today") - df2["date_of_joining"])

In [48]:
df2["tenure_years"] = df2["tenure_years"]/365.25

In [49]:
df2["tenure_years"]

0       5.582478
1       4.703628
2      12.317591
3       3.247091
4      15.129363
         ...
213     1.782341
214    10.447639
215     6.346338
216          NaN
217     2.872005
Name: tenure_years, Length: 218, dtype: float64

In [51]:
df2["age"].value_counts(dropna = False)

age
NaN     20
28.0    17
33.0    14
32.0    14
31.0    14
25.0    11
24.0     9
30.0     9
36.0     8
27.0     8
34.0     8
20.0     8
26.0     7
38.0     7
39.0     7
29.0     7
41.0     5
37.0     5
48.0     4
35.0     4
44.0     4
45.0     4
23.0     4
49.0     3
22.0     3
40.0     3
47.0     2
43.0     2
42.0     2
52.0     2
21.0     2
51.0     1
Name: count, dtype: int64

In [63]:
df2["age"] = df2["age"].fillna(df2["age"].median())

In [64]:
df2["age"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 218 entries, 0 to 217
Series name: age
Non-Null Count  Dtype
--------------  -----
218 non-null    float64
dtypes: float64(1)
memory usage: 1.8 KB

In [66]:
df2.describe()

,age,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,tenure_years
count,218.000000,208,218.000000,1.550000e+02,199.000000,197.000000,205.000000,218.000000,208.000000
mean,32.270642,2018-02-24 21:13:50.769230848,8.761468,1.561213e+05,3867.784824,3.318782,39.045854,3.949541,8.531459
min,20.000000,2010-01-24 00:00:00,0.000000,-4.500000e+04,882.690000,1.300000,-12.000000,0.000000,1.593429
25%,28.000000,2014-11-06 18:00:00,1.000000,7.351244e+04,2749.880000,2.800000,36.400000,3.000000,4.980151
50%,31.500000,2018-03-25 12:00:00,6.000000,8.850674e+04,3552.160000,3.300000,39.900000,4.000000,8.453114
75%,36.000000,2021-09-14 00:00:00,12.000000,1.086638e+05,4700.440000,3.900000,42.900000,5.000000,11.833676
max,52.000000,2025-02-02 00:00:00,99.000000,9.999999e+06,10860.790000,5.000000,51.400000,9.000000,16.618754
std,7.016121,NaN,12.884742,7.964329e+05,1738.271058,0.760573,7.482204,1.932555,4.310355

### DUPLICATES

In [68]:
df2.duplicated().value_counts()

False    206
True      12
Name: count, dtype: int64

In [69]:
df2[df2.duplicated()]

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,exit_date,tenure_years
49,E1027,Meera Smith,31.0,hr,Perth,2016-06-08,6,NaN,2843.88,3.2,NaN,2,True,meera.smith@corp.com,NaN,10.247775
105,E1145,James Patel,28.0,None,Perth,2018-03-29,8,106918.55,4572.68,NaN,39.2,1,False,james.patel@corp.com,NaN,8.443532
134,E1048,Vikram Brown,33.0,finance,Sydney,2021-09-14,4,99920.31,3552.16,3.5,42.8,4,False,vikram.brown@corp.com,NaN,4.980151
136,E1076,Sneha Wong,52.0,finance,Sydney,2023-05-23,29,173289.47,5001.23,3.3,37.6,1,True,sneha.wong@corp.com,NaN,3.293634
138,E1107,Aarav Sharma,40.0,support,Bangalore,2015-11-12,18,122829.74,5027.28,4.5,39.1,8,True,aarav.sharma@corp.com,NaN,10.819986
177,E1087,Meera Brown,32.0,engineering,Perth,2024-03-12,10,106664.52,6530.25,3.9,NaN,7,False,meera.brown@corp.com,NaN,2.488706
192,E1006,Hassan Tanaka,28.0,hr,Sydney,2010-02-12,2,74488.87,3113.35,4.3,43.2,7,True,hassan.tanaka@corp.com,NaN,16.566735
198,E1127,Priya Kumar,31.5,None,Bangalore,2018-03-22,11,84984.56,2322.15,3.1,37.8,1,False,priya.kumar@corp.com,NaN,8.462697
201,E1167,Noah Garcia,28.0,sales,Brisbane,2022-08-23,5,85829.66,4258.69,3.3,40.0,7,True,noah.garcia@corp.com,NaN,4.041068
202,E1136,Karan Nair,32.0,support,Singapore,2019-08-01,8,NaN,NaN,2.0,30.5,4,False,karan.nair@corp.com,NaN,7.101985
203,E1042,Fatima Smith,24.0,sales,Singapore,2012-06-10,0,78722.66,4719.00,4.1,38.2,4,NaN,fatima.smith@corp.com,NaN,14.242300
213,E1016,Liam Brown,30.0,hr,Brisbane,2024-11-25,4,72999.99,2982.06,4.3,37.2,3,True,liam.brown@corp.com,NaN,1.782341

In [70]:
df2 = df2.drop_duplicates()

In [71]:
df2["emp_id"].duplicated().sum()

np.int64(6)

In [74]:
df2 = df2.drop(columns = ["null"])

In [76]:
df2.columns

Index(['emp_id', 'name', 'age', 'department', 'city', 'date_of_joining',
       'experience_years', 'salary', 'bonus', 'performance score',
       'Work Hours per Week ', 'Projects Completed', 'remote', 'email',
       'exit_date', 'tenure_years'],
      dtype='object')

In [77]:
df2.loc[:,"nulls"] = df2.isna().sum(axis = 1)

In [78]:
df2 = df2.sort_values("nulls")

In [79]:
df2 = df2.drop_duplicates(subset = 'emp_id' , keep = "first")
df2 = df2.drop(columns = "nulls")

In [81]:
df2["has_left"] = df2["exit_date"].notna()

In [82]:
df2 = df2.drop(columns = ["exit_date"])

In [83]:
df2["department"] = df2["department"].fillna("Unknown")

In [84]:
df2["department"].value_counts()

department
hr                  37
marketing           34
sales               33
finance             30
engineering         28
support             25
Unknown             12
customer support     1
Name: count, dtype: int64

In [85]:
## fills multiple columns at once
df2 = df2.fillna({"city" : "Unknown" , "Bonus" : 0})

In [86]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 52 to 68
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   emp_id                200 non-null    object
 1   name                  200 non-null    object
 2   age                   200 non-null    float64
 3   department            200 non-null    object
 4   city                  200 non-null    object
 5   date_of_joining       191 non-null    datetime64[ns]
 6   experience_years      200 non-null    int64
 7   salary                145 non-null    float64
 8   bonus                 182 non-null    float64
 9   performance score     186 non-null    float64
 10  Work Hours per Week   190 non-null    float64
 11  Projects Completed    200 non-null    int64
 12  remote                192 non-null    object
 13  email                 200 non-null    object
 14  tenure_years          191 non-null    float64
 15  has_left              200 non-null    bool
dtypes: bool(1), datetime64[ns](1), float64(6), int64(2), object(6)
memory usage: 25.2+ KB

### group aware filling

In [89]:
df2.loc[df2["salary"] < 20000 , "salary"] = None

In [93]:
df2["salary"].value_counts(dropna = False)

salary
NaN          57
84258.06      1
91973.11      1
69688.83      1
91492.85      1
             ..
142378.07     1
124517.83     1
103370.63     1
62644.06      1
81032.37      1
Name: count, Length: 144, dtype: int64

In [95]:
df2["department"] = df2["department"].replace({
    "support" : "customer support"
})

In [96]:
df2["department"] = df2["department"].replace({
    "Unknown" : None
})

In [98]:
df2["department"].value_counts(dropna = False)

department
hr                  37
marketing           34
sales               33
finance             30
engineering         28
customer support    26
None                12
Name: count, dtype: int64

In [101]:
df2["salary"] = df2["salary"].fillna(df2.groupby("department")["salary"].transform("median"))

In [102]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 52 to 68
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   emp_id                200 non-null    object
 1   name                  200 non-null    object
 2   age                   200 non-null    float64
 3   department            188 non-null    object
 4   city                  200 non-null    object
 5   date_of_joining       191 non-null    datetime64[ns]
 6   experience_years      200 non-null    int64
 7   salary                198 non-null    float64
 8   bonus                 182 non-null    float64
 9   performance score     186 non-null    float64
 10  Work Hours per Week   190 non-null    float64
 11  Projects Completed    200 non-null    int64
 12  remote                192 non-null    object
 13  email                 200 non-null    object
 14  tenure_years          191 non-null    float64
 15  has_left              200 non-null    bool
dtypes: bool(1), datetime64[ns](1), float64(6), int64(2), object(6)
memory usage: 25.2+ KB

In [103]:
df2["salary"] = df2["salary"].fillna(df2["salary"].median())

In [104]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 52 to 68
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   emp_id                200 non-null    object
 1   name                  200 non-null    object
 2   age                   200 non-null    float64
 3   department            188 non-null    object
 4   city                  200 non-null    object
 5   date_of_joining       191 non-null    datetime64[ns]
 6   experience_years      200 non-null    int64
 7   salary                200 non-null    float64
 8   bonus                 182 non-null    float64
 9   performance score     186 non-null    float64
 10  Work Hours per Week   190 non-null    float64
 11  Projects Completed    200 non-null    int64
 12  remote                192 non-null    object
 13  email                 200 non-null    object
 14  tenure_years          191 non-null    float64
 15  has_left              200 non-null    bool
dtypes: bool(1), datetime64[ns](1), float64(6), int64(2), object(6)
memory usage: 25.2+ KB

In [105]:
df2["remote"].value_counts(dropna = False)

remote
True     101
False     91
NaN        8
Name: count, dtype: int64

In [106]:
df2[df2["remote"].isna()]

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,tenure_years,has_left
210,E1092,Aarav Smith,20.0,marketing,Bangalore,2016-07-30,0,76747.545,3089.64,2.6,41.5,6,NaN,aarav.smith@corp.com,10.105407,False
170,E1093,Wei Patel,31.5,engineering,Melbourne,2018-08-14,11,109233.970,7459.77,3.4,30.1,4,NaN,wei.patel@corp.com,8.065708,True
167,E1042,Fatima Smith,24.0,sales,Singapore,2012-06-10,0,78722.660,4719.00,4.1,38.2,4,NaN,fatima.smith@corp.com,14.242300,False
204,E1110,Wei Reddy,31.5,customer support,MELBOURNE,2020-12-17,16,100116.080,3840.47,3.1,45.9,3,NaN,wei.reddy@corp.com,5.722108,False
76,E1146,Noah Nair,49.0,sales,Sydney,2018-07-26,24,161826.640,6754.46,3.6,39.4,3,NaN,noah.nair@corp.com,8.117728,False
28,E1099,Rohan Ali,28.0,marketing,Sydney,2017-01-18,99,80416.620,3071.24,3.0,39.8,1,NaN,rohan.ali@corp.com,9.634497,False
190,E1188,Noah Reddy,41.0,sales,Bangalore,2019-03-05,21,134533.200,NaN,3.5,43.2,7,NaN,noah.reddy@corp.com,7.509925,False
38,E1116,isha sharma,33.0,hr,Melbourne,2015-10-29,8,73744.430,2906.45,3.4,41.3,6,NaN,isha.sharma@corp.com,10.858316,False

In [108]:
df2.groupby("department")["salary"].agg(["mean" , "median" , "count" , "max" , "size"])

                           mean      median  count         max  size
department
customer support   75317.011538   72516.295     26   122829.74    26
engineering       112406.770357  109233.970     28   171186.20    28
finance           443220.551333  110290.260     30  9999999.00    30
hr                 74300.343243   73744.430     37   115385.81    37
marketing          82523.346176   76747.545     34   153627.16    34
sales              98659.682121   96558.700     33   161826.64    33

In [109]:
df2.groupby("department").agg(
    headcount=("emp_id", "count"),
    med_salary=("salary", "median"),
    avg_age=("age", "mean"),
)

                  headcount  med_salary    avg_age
department
customer support         26   72516.295  32.057692
engineering              28  109233.970  32.696429
finance                  30  110290.260  33.216667
hr                       37   73744.430  31.337838
marketing                34   76747.545  31.250000
sales                    33   96558.700  32.409091

In [110]:
df2.groupby(["department", "city"])["salary"].median()

department        city
customer support   Bangalore     122829.740
                  BANGALORE       96346.190
                  Bangalore       72516.295
                  Brisbane        71896.595
                  MELBOURNE       73508.365
                                    ...
sales             Singapore       80340.780
                  Sydney          83003.640
                  Unknown         88329.455
                  brisbane        96558.700
                  perth           72054.450
Name: salary, Length: 69, dtype: float64

In [112]:
dept_med = df2.groupby("department")["salary"].transform("median")

In [113]:
df2["salary_vs_dept"] = df2["salary"] / dept_med

In [114]:
df2

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,tenure_years,has_left,salary_vs_dept
52,E1186,Vikram Garcia,30.0,marketing,Bangalore,2017-09-20,5,84258.06,3127.41,2.7,45.9,8,False,vikram.garcia@corp.com,8.963723,True,1.097860
175,E1083,Emma Patel,31.0,hr,Perth,2017-09-23,9,76315.98,4233.80,4.4,34.5,1,False,emma.patel@corp.com,8.955510,True,1.034871
121,E1126,Vikram Reddy,23.0,customer support,Bangalore,2018-06-18,2,82661.92,4834.13,3.8,48.1,3,True,vikram.reddy@corp.com,8.221766,True,1.139908
73,E1150,Sophia Smith,32.0,engineering,Melbourne,2020-09-02,8,125678.12,3738.15,2.6,42.2,2,True,sophia.smith@corp.com,6.012320,True,1.150541
87,E1005,Meera Garcia,37.0,customer support,BANGALORE,2023-05-12,11,96346.19,5033.02,3.3,47.2,4,False,meera.garcia@corp.com,3.323751,False,1.328614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,E1168,Yuki Garcia,28.0,hr,Unknown,2010-04-04,2,73744.43,3647.05,NaN,39.7,5,True,yuki.garcia@corp.com,16.427105,False,1.000000
89,E1147,Vikram Brown,29.0,finance,Brisbane,NaT,2,89103.46,4196.43,NaN,33.6,4,True,vikram.brown@corp.com,NaN,False,0.807900
172,E1118,Liam Chen,44.0,marketing,Melbourne,NaT,24,145057.18,4168.20,3.2,NaN,2,True,liam.chen@corp.com,NaN,False,1.890056
108,E1162,Rohan Sharma,30.0,None,Perth,NaT,5,87412.74,2375.63,3.9,33.2,3,False,rohan.sharma@corp.com,NaN,False,NaN
68,E1036,James Wong,30.0,customer support,Unknown,NaT,1,81032.37,NaN,3.3,40.8,4,False,james.wong@corp.com,NaN,False,1.117437

### merge

In [115]:
df2["department"].value_counts(dropna = False)

department
hr                  37
marketing           34
sales               33
finance             30
engineering         28
customer support    26
None                12
Name: count, dtype: int64

In [116]:
budgets = pd.DataFrame({
    "department": ["engineering", "finance", "hr", "marketing", "sales", "support"],
    "budget": [2_000_000, 1_500_000, 800_000, 900_000, 1_800_000, 700_000],
})

len_before = len(df2)
df2 = df2.merge(budgets , on = "department" , how = "left")
len_after = len(df2)

print(len_after == len_before)

True

### Pivot_table

In [121]:
df2["city"] = df2["city"].str.strip().str.lower()

In [122]:
df2.pivot_table(values = "salary" , index = "department" , columns = "city" , aggfunc = "median")

city,bangalore,brisbane,melbourne,perth,singapore,sydney,unknown
department,,,,,,,
customer support,82661.920,71896.5950,71007.70,57441.725,73270.5925,72516.295,81032.370
engineering,109233.970,109233.9700,109233.97,107379.050,106302.3000,109690.750,NaN
finance,110290.260,89103.4600,110290.26,140908.290,125593.9500,120939.225,110290.260
hr,68194.245,72537.4600,73744.43,73744.430,73744.4300,73744.430,73744.430
marketing,76747.545,70760.4025,72833.26,76747.545,85981.6200,76747.545,91492.850
sales,96558.700,100682.5850,98111.04,96558.700,80340.7800,96558.700,88329.455

In [124]:
pd.crosstab(df2["department"] , df2["city"])

city,bangalore,brisbane,melbourne,perth,singapore,sydney,unknown
department,,,,,,,
customer support,5,4,5,2,6,3,1
engineering,1,5,9,6,4,3,0
finance,9,3,5,4,2,4,3
hr,6,6,2,7,5,10,1
marketing,9,2,5,8,3,6,1
sales,5,6,3,8,4,5,2

### np_where

In [125]:
import numpy as np


df2["post"] =  np.where(df2["experience_years"] > 8 , "senior" , "junior")

In [127]:
df2 = df2.drop(columns = "post")

In [129]:
df2["post"] = np.where(df2["experience_years"].isna() , None , np.where(df2["experience_years"] > 8 , "Senior" , "Junior"))

In [130]:
df2["salary_band"] = np.select(
    [df2["salary"] < 75000, df2["salary"] < 110000],
    ["low",                  "mid"                 ],
    default="high"
)

df2["salary_band"].value_counts()

salary_band
mid     99
low     58
high    43
Name: count, dtype: int64

In [131]:
df2["salary_band2"] = pd.cut(
    df2["salary"],
    bins=[0, 75000, 110000, np.inf],
    labels=["low", "mid", "high"]
)

df2["salary_band2"].value_counts()

salary_band2
mid     99
low     58
high    43
Name: count, dtype: int64