In [1]:
%pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

df = pd.read_csv("messy_employees.csv")

In [86]:
import pandas as pd

df1 = pd.read_csv("messy_employees.csv")

In [87]:
mask = df1['age'] > 40

df1[(df1['age'] > 40)]

In [89]:
df[mask]

/var/folders/8t/z8t0kpz1639_xr5xvw0zqb8h0000gn/T/ipykernel_24337/2581737305.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[mask]

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,has_left,tenure_years,joining_year,joining_month
159,E1100,Rohan Reddy,41.0,engineering,perth,2023-12-11,17,153942.530,6889.69,3.7,38.5,2,True,rohan.reddy@corp.com,False,2.740589,2023.0,12.0
79,E1160,Karan Ali,41.0,marketing,perth,2013-03-28,13,119699.160,4778.03,2.8,41.6,6,True,karan.ali@corp.com,False,13.445585,2013.0,3.0
76,E1146,Noah Nair,49.0,sales,sydney,2018-07-26,24,161826.640,6754.46,3.6,39.4,3,False,noah.nair@corp.com,False,8.117728,2018.0,7.0
63,E1076,Sneha Wong,52.0,finance,sydney,2023-05-23,29,173289.470,5001.23,3.3,37.6,1,True,sneha.wong@corp.com,False,3.293634,2023.0,5.0
95,E1064,Fatima Kumar,48.0,finance,perth,2023-06-17,23,142378.070,4031.58,2.7,40.4,5,False,fatima.kumar@corp.com,False,3.225188,2023.0,6.0
139,E1170,Yuki Nair,43.0,hr,brisbane,2017-10-21,14,101684.570,3528.31,2.3,38.3,6,False,,False,8.878850,2017.0,10.0
124,E1090,Olivia Singh,49.0,engineering,singapore,2019-07-03,25,190992.360,8402.67,4.2,42.2,4,False,olivia.singh@corp.com,False,7.181383,2019.0,7.0
152,E1033,Arjun Reddy,51.0,engineering,melbourne,2013-03-09,26,171186.200,6439.54,2.5,39.1,7,False,arjun.reddy@corp.com,False,13.497604,2013.0,3.0
102,E1007,Priya Chen,45.0,sales,brisbane,2020-04-19,18,126866.880,7075.12,3.7,39.0,4,False,priya.chen@corp.com,False,6.384668,2020.0,4.0
101,E1081,Wei Nair,45.0,support,bangalore,2014-10-10,16,115697.650,5881.23,3.4,40.9,4,False,wei.nair@corp.com,False,11.909651,2014.0,10.0
61,E1028,Ananya Jones,45.0,hr,bangalore,2023-02-09,19,115385.810,5816.75,3.6,42.3,2,False,ananya.jones@corp.com,False,3.575633,2023.0,2.0
27,E1163,Fatima Ali,41.0,sales,singapore,2022-01-14,19,146843.570,5364.19,3.2,45.1,5,False,fatima.ali@corp.com,False,4.646133,2022.0,1.0
58,E1129,Hassan Ali,44.0,support,singapore,2017-01-04,17,84377.360,5889.08,5.0,34.8,4,True,hassan.ali@corp.com,False,9.672827,2017.0,1.0
57,E1013,Liam Jones,43.0,finance,perth,2017-11-26,17,148093.290,7274.97,3.4,38.4,5,False,liam.jones@corp.com,False,8.780287,2017.0,11.0
193,E1055,Olivia Singh,48.0,engineering,melbourne,2022-12-25,22,109908.665,8268.73,3.6,39.8,3,True,olivia.singh@corp.com,False,3.701574,2022.0,12.0
148,E1198,Meera Jones,49.0,sales,brisbane,2011-05-24,24,142344.140,NaN,3.1,47.3,5,False,meera.jones@corp.com,False,15.290897,2011.0,5.0
190,E1188,Noah Reddy,41.0,sales,bangalore,2019-03-05,21,134533.200,NaN,3.5,43.2,7,False,noah.reddy@corp.com,False,7.509925,2019.0,3.0
131,E1053,Aarav Sharma,31.0,marketing,perth,2023-10-12,4,77513.970,3032.57,2.9,28.7,4,True,aarav.sharma@corp.com,False,2.904860,2023.0,10.0
59,E1173,Liam Nair,45.0,marketing,brisbane,2013-05-17,24,76933.520,4321.40,2.5,37.5,3,True,liam.nair@corp.com,False,13.308693,2013.0,5.0
46,E1066,Aarav Ali,44.0,support,singapore,2023-04-10,18,111980.120,NaN,3.2,39.6,4,True,aarav.ali@corp.com,False,3.411362,2023.0,4.0
37,E1057,Sophia Tanaka,41.0,finance,NaN,2017-03-12,15,142867.920,4523.35,2.7,41.0,5,False,sophia.tanaka@corp.com,False,9.489391,2017.0,3.0
19,E1109,Emma Garcia,47.0,hr,bangalore,2019-04-03,21,75294.230,3971.19,2.7,34.0,3,False,emma.garcia@corp.com,False,7.430527,2019.0,4.0
217,E1175,Wei Nair,47.0,None,brisbane,2023-10-24,26,138346.240,5404.73,3.3,0.0,2,False,wei.nair@corp.com,False,2.872005,2023.0,10.0
125,E1199,Sneha Tanaka,42.0,hr,bangalore,2020-06-16,15,101090.150,2960.25,3.5,NaN,2,True,sneha.tanaka@corp.com,False,6.225873,2020.0,6.0
206,E1072,Wei Khan,31.0,finance,NaN,2020-02-06,0,84192.920,3085.45,2.8,42.8,5,True,wei.khan@corp.com,False,6.584531,2020.0,2.0
111,E1079,Fatima Chen,31.0,finance,bangalore,2024-08-07,2,91209.980,NaN,4.1,38.8,2,True,fatima.chen@corp.com,False,2.083504,2024.0,8.0
170,E1093,Wei Patel,31.0,engineering,melbourne,2018-08-14,11,109908.665,7459.77,3.4,30.1,4,False,wei.patel@corp.com,True,8.065708,2018.0,8.0
216,E1196,Aarav Ali,44.0,marketing,singapore,NaT,24,153627.160,10278.26,4.2,35.9,4,True,aarav.ali@corp.com,False,NaN,NaN,NaN
172,E1118,Liam Chen,44.0,marketing,melbourne,NaT,24,145057.180,4168.20,3.2,NaN,2,True,liam.chen@corp.com,False,NaN,NaN,NaN

In [3]:
df.head()

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,exit_date
0,E1139,Rohan Tanaka,33.0,Sales,NaN,06/02/2021,8,96558.7,2723.68,2.9,40.0,2,1,rohan.tanaka@corp.com,NaN
1,E1065,Vikram Chen,32.0,Finance,Melbourne,2021-12-24,5,95487.76,1812.91,2.1,49.2,3,N,vikram.chen@corp.com,NaN
2,E1095,Arjun Ali,24.0,sales,PERTH,2014-05-14,0,NaN,882.69,1.6,36.8,3,No,,NaN
3,E1022,Arjun Jones,27.0,support,Singapore,2023-06-09,0,67002.04,2877.76,3.4,45.7,2,Yes,arjun.jones@corp.com,NaN
4,E1063,Hassan Wong,30.0,Human Resources,Singapore,2011-07-22,0,63310.87,1661.07,2.8,37.0,4,Yes,hassan.wong@corp.com,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   emp_id                218 non-null    object
 1   name                  218 non-null    object
 2   age                   202 non-null    float64
 3   department            218 non-null    object
 4   city                  207 non-null    object
 5   date_of_joining       218 non-null    object
 6   experience_years      218 non-null    int64
 7   salary                190 non-null    object
 8   bonus                 199 non-null    float64
 9   performance score     197 non-null    float64
 10  Work Hours per Week   205 non-null    float64
 11  Projects Completed    218 non-null    int64
 12  remote                218 non-null    object
 13  email                 218 non-null    object
 14  exit_date             7 non-null      object
dtypes: float64(4), int64(2), object(9)
memory usage: 25.7+ KB

In [5]:
# returns true for the non null values and false for null values
df['has_left'] = df['exit_date'].notna()
df = df.drop(columns = ['exit_date'])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   emp_id                218 non-null    object
 1   name                  218 non-null    object
 2   age                   202 non-null    float64
 3   department            218 non-null    object
 4   city                  207 non-null    object
 5   date_of_joining       218 non-null    object
 6   experience_years      218 non-null    int64
 7   salary                190 non-null    object
 8   bonus                 199 non-null    float64
 9   performance score     197 non-null    float64
 10  Work Hours per Week   205 non-null    float64
 11  Projects Completed    218 non-null    int64
 12  remote                218 non-null    object
 13  email                 218 non-null    object
 14  has_left              218 non-null    bool
dtypes: bool(1), float64(4), int64(2), object(8)
memory usage: 24.2+ KB

In [7]:
df['has_left'].value_counts()

has_left
False    211
True       7
Name: count, dtype: int64

In [8]:
df['age'].value_counts()

age
28.0     17
33.0     14
32.0     14
31.0     14
25.0     11
24.0      9
30.0      9
27.0      8
34.0      8
20.0      8
36.0      8
26.0      7
39.0      7
29.0      7
38.0      7
37.0      5
41.0      5
48.0      4
44.0      4
45.0      4
23.0      4
35.0      4
22.0      3
49.0      3
150.0     3
40.0      3
47.0      2
21.0      2
43.0      2
52.0      2
42.0      2
51.0      1
999.0     1
Name: count, dtype: int64

In [9]:
df['age'] 

'''-> returns series '''

df[['age']]

'''-> returns list'''

'-> returns list'

In [10]:
df['age'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 218 entries, 0 to 217
Series name: age
Non-Null Count  Dtype
--------------  -----
202 non-null    float64
dtypes: float64(1)
memory usage: 1.8 KB

In [11]:
df['age'].sort_values().head(10)

156    20.0
56     20.0
70     20.0
103    20.0
120    20.0
39     20.0
209    20.0
210    20.0
40     21.0
75     21.0
Name: age, dtype: float64

In [12]:
df['age'].sort_values().tail(10)

82    NaN
90    NaN
114   NaN
151   NaN
157   NaN
176   NaN
198   NaN
199   NaN
204   NaN
205   NaN
Name: age, dtype: float64

In [13]:

## the below output is showing that 4 people have age greater than 75 while 214 its not
(df['age'] > 75).value_counts()

age
False    214
True       4
Name: count, dtype: int64

In [14]:
df.loc[df['age'] > 75 , "age"]

111    150.0
131    150.0
170    150.0
206    999.0
Name: age, dtype: float64

In [15]:
## now the rows which had age > 75 will be having nan age 
df.loc[df["age"] > 75, "age"] = None

In [16]:
df['age'].describe()

count    198.000000
mean      32.348485
std        7.359153
min       20.000000
25%       27.000000
50%       31.500000
75%       37.000000
max       52.000000
Name: age, dtype: float64

In [17]:
df['salary'].value_counts()

salary
85829.66      2
78722.66      2
$84,392.96    2
$64,862.90    2
106664.52     2
             ..
64238.05      1
161826.64     1
65626.59      1
119699.16     1
138346.24     1
Name: count, Length: 177, dtype: int64

In [18]:
s = df['salary']
s = s.str.replace("$","",regex = False)
s = s.str.replace(",","",regex = False)
s = s.str.replace(" AUD","",regex = False)

In [19]:
s.info()

<class 'pandas.core.series.Series'>
RangeIndex: 218 entries, 0 to 217
Series name: salary
Non-Null Count  Dtype
--------------  -----
190 non-null    object
dtypes: object(1)
memory usage: 1.8+ KB

In [20]:
df['salary'] = s

In [21]:
df['salary'] = pd.to_numeric(df['salary'], errors = 'coerce')

In [22]:
df['salary'].describe()

count    1.900000e+02
mean     1.457106e+05
std      7.193670e+05
min     -4.500000e+04
25%      7.442996e+04
50%      8.891286e+04
75%      1.094049e+05
max      9.999999e+06
Name: salary, dtype: float64

In [23]:
df.loc[df['salary'] < 20000 , "salary"] = None
df.loc[df['salary'] > 1000000 , "salary"] = None

In [24]:
df['salary'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 218 entries, 0 to 217
Series name: salary
Non-Null Count  Dtype
--------------  -----
187 non-null    float64
dtypes: float64(1)
memory usage: 1.8 KB

In [25]:
df['salary'].describe()

count       187.000000
mean      95053.516417
std       27997.012717
min       42479.890000
25%       74488.870000
50%       89011.360000
75%      109367.790000
max      190992.360000
Name: salary, dtype: float64

In [26]:
df['department'].value_counts()

department
HR                  27
Engineering         26
Finance             26
Sales               23
Support             20
Marketing           18
?                   16
Mktg                11
support              7
SALES                6
hr                   6
FINANCE              5
sales                5
marketing            5
Human Resources      4
H.R.                 4
Engg                 2
finance              2
engineering          2
Customer Support     1
ENGINEERING          1
Sales                1
Name: count, dtype: int64

In [27]:
df['department'] = df['department'].str.strip().str.lower()

In [28]:
df['department'].value_counts()

department
sales               35
finance             33
hr                  33
engineering         29
support             27
marketing           23
?                   16
mktg                11
human resources      4
h.r.                 4
engg                 2
customer support     1
Name: count, dtype: int64

In [29]:
df["department"] = df["department"].replace({
    # your six entries here
    "h.r." : "hr",
    "mktg" : "marketing",
    "human resources" : "hr",
    "engg" : "engineering",
    "customer support" : "support"
})

In [30]:
df['department'].value_counts()

department
hr             41
sales          35
marketing      34
finance        33
engineering    31
support        28
?              16
Name: count, dtype: int64

In [31]:
df.loc[df['department'] == '?' , 'department']

17     ?
23     ?
24     ?
29     ?
45     ?
105    ?
108    ?
109    ?
115    ?
119    ?
158    ?
176    ?
184    ?
198    ?
211    ?
217    ?
Name: department, dtype: object

In [32]:
df['department'] = df['department'].replace({
    "?" : None
})

In [33]:
df['department'].value_counts()

department
hr             41
sales          35
marketing      34
finance        33
engineering    31
support        28
Name: count, dtype: int64

In [34]:
df['city'].value_counts()

city
Bangalore      35
Perth          34
Brisbane       27
Melbourne      26
Sydney         26
Singapore      22
PERTH           6
 Sydney         5
 Bangalore      4
BANGALORE       3
perth           3
singapore       3
melbourne       3
MELBOURNE       2
SYDNEY          2
sydney          1
 Melbourne      1
 Singapore      1
brisbane        1
 Brisbane       1
BRISBANE        1
Name: count, dtype: int64

In [35]:
df['city'] = df['city'].str.lower()

In [36]:
df['city'].value_counts()

city
perth          43
bangalore      38
melbourne      31
sydney         29
brisbane       29
singapore      25
 sydney         5
 bangalore      4
 melbourne      1
 singapore      1
 brisbane       1
Name: count, dtype: int64

In [37]:
df['city'] = df['city'].str.strip().str.lower()

In [38]:
df['city'].value_counts(dropna = False)

city
perth        43
bangalore    42
sydney       34
melbourne    32
brisbane     30
singapore    26
NaN          11
Name: count, dtype: int64

In [39]:
df['remote'].value_counts()

remote
Yes      72
No       71
1        13
no       12
0        11
Y        11
TRUE     10
FALSE     9
N         6
yes       3
Name: count, dtype: int64

In [40]:
df["remote"] = df["remote"].map({
    "Yes": True,  "yes": True,  "Y": True,  "TRUE": True,  "1": True,
    "No": False,  "no": False,  "N": False, "FALSE": False, "0": False,
})

df["remote"].value_counts(dropna=False)

remote
True     109
False    109
Name: count, dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   emp_id                218 non-null    object
 1   name                  218 non-null    object
 2   age                   198 non-null    float64
 3   department            202 non-null    object
 4   city                  207 non-null    object
 5   date_of_joining       218 non-null    object
 6   experience_years      218 non-null    int64
 7   salary                187 non-null    float64
 8   bonus                 199 non-null    float64
 9   performance score     197 non-null    float64
 10  Work Hours per Week   205 non-null    float64
 11  Projects Completed    218 non-null    int64
 12  remote                218 non-null    bool
 13  email                 218 non-null    object
 14  has_left              218 non-null    bool
dtypes: bool(2), float64(5), int64(2), object(6)
memory usage: 22.7+ KB

In [42]:
df['date_of_joining'].value_counts(dropna = False)

date_of_joining
-              10
01/08/2019      2
2023-06-17      2
2022-12-25      2
12/04/2015      2
               ..
02-Sep-2020     1
2020-09-06      1
2018-07-26      1
2019-08-21      1
2023-10-24      1
Name: count, Length: 191, dtype: int64

In [44]:
df['date_of_joining'] = pd.to_datetime(
    df["date_of_joining"],
    ## in the data there are various formats of data so to change them to a proper datetime format , format = "mixed" is required
    format = "mixed",
    ## days should comes first the format should be dd/mm/yyyy
    dayfirst = True,
    ## without this any unparsed value can cause an error in the code
    errors = "coerce"
)

In [46]:
df['date_of_joining'].describe()

count                              208
mean     2018-02-24 21:13:50.769230848
min                2010-01-24 00:00:00
25%                2014-11-06 18:00:00
50%                2018-03-25 12:00:00
75%                2021-09-14 00:00:00
max                2025-02-02 00:00:00
Name: date_of_joining, dtype: object

In [48]:
df['date_of_joining'].isna().sum()

np.int64(10)

In [49]:
df['tenure_years'] = (pd.Timestamp("today") - df["date_of_joining"]).dt.days / 365.25

## pd.timestamp("todays") -> takes todays date
## dt.days -> converts the result into days
#/365.25 -> convert the number of days to years

In [51]:
df['tenure_years'].describe()

count    208.000000
mean       8.531459
std        4.310355
min        1.593429
25%        4.980151
50%        8.453114
75%       11.833676
max       16.618754
Name: tenure_years, dtype: float64

In [52]:
df['joining_year'] = df["date_of_joining"].dt.year

In [61]:
df['joining_month'] = df["date_of_joining"].dt.month

In [62]:
df['joining_month']

0       2.0
1      12.0
2       5.0
3       6.0
4       7.0
       ...
213    11.0
214     3.0
215     5.0
216     NaN
217    10.0
Name: joining_month, Length: 218, dtype: float64

In [66]:
df[df.duplicated()]

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,has_left,tenure_years,joining_year,joining_month
49,E1027,Meera Smith,31.0,hr,perth,2016-06-08,6,64862.90,2843.88,3.2,NaN,2,True,meera.smith@corp.com,False,10.247775,2016.0,6.0
105,E1145,James Patel,28.0,None,perth,2018-03-29,8,106918.55,4572.68,NaN,39.2,1,False,james.patel@corp.com,False,8.443532,2018.0,3.0
134,E1048,Vikram Brown,33.0,finance,sydney,2021-09-14,4,99920.31,3552.16,3.5,42.8,4,False,vikram.brown@corp.com,False,4.980151,2021.0,9.0
136,E1076,Sneha Wong,52.0,finance,sydney,2023-05-23,29,173289.47,5001.23,3.3,37.6,1,True,sneha.wong@corp.com,False,3.293634,2023.0,5.0
138,E1107,Aarav Sharma,40.0,support,bangalore,2015-11-12,18,122829.74,5027.28,4.5,39.1,8,True,aarav.sharma@corp.com,False,10.819986,2015.0,11.0
177,E1087,Meera Brown,32.0,engineering,perth,2024-03-12,10,106664.52,6530.25,3.9,NaN,7,False,meera.brown@corp.com,False,2.488706,2024.0,3.0
192,E1006,Hassan Tanaka,28.0,hr,sydney,2010-02-12,2,74488.87,3113.35,4.3,43.2,7,True,hassan.tanaka@corp.com,False,16.566735,2010.0,2.0
198,E1127,Priya Kumar,NaN,None,bangalore,2018-03-22,11,84984.56,2322.15,3.1,37.8,1,False,priya.kumar@corp.com,False,8.462697,2018.0,3.0
201,E1167,Noah Garcia,28.0,sales,brisbane,2022-08-23,5,85829.66,4258.69,3.3,40.0,7,True,noah.garcia@corp.com,False,4.041068,2022.0,8.0
202,E1136,Karan Nair,32.0,support,singapore,2019-08-01,8,84392.96,NaN,2.0,30.5,4,False,karan.nair@corp.com,False,7.101985,2019.0,8.0
203,E1042,Fatima Smith,24.0,sales,singapore,2012-06-10,0,78722.66,4719.00,4.1,38.2,4,False,fatima.smith@corp.com,False,14.242300,2012.0,6.0
213,E1016,Liam Brown,30.0,hr,brisbane,2024-11-25,4,72999.99,2982.06,4.3,37.2,3,True,liam.brown@corp.com,False,1.782341,2024.0,11.0

In [68]:
df = df.drop_duplicates()

In [69]:
df["emp_id"].duplicated().sum()

np.int64(6)

In [70]:
df[df["emp_id"].duplicated(keep=False)].sort_values("emp_id")

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,has_left,tenure_years,joining_year,joining_month
30,E1055,Olivia Singh,48.0,engineering,melbourne,2022-12-25,22,NaN,8268.73,NaN,39.8,3,True,olivia.singh@corp.com,False,3.701574,2022.0,12.0
193,E1055,Olivia Singh,48.0,engineering,melbourne,2022-12-25,22,NaN,8268.73,3.6,39.8,3,True,olivia.singh@corp.com,False,3.701574,2022.0,12.0
95,E1064,Fatima Kumar,48.0,finance,perth,2023-06-17,23,142378.07,4031.58,2.7,40.4,5,False,fatima.kumar@corp.com,False,3.225188,2023.0,6.0
146,E1064,Fatima Kumar,48.0,finance,perth,2023-06-17,23,NaN,4031.58,NaN,40.4,5,False,fatima.kumar@corp.com,False,3.225188,2023.0,6.0
29,E1088,Ananya Garcia,31.0,None,NaN,2015-04-12,9,99524.45,3764.97,4.2,42.9,2,False,ananya.garcia@corp.com,False,11.405886,2015.0,4.0
158,E1088,Ananya Garcia,31.0,None,NaN,2015-04-12,9,NaN,3764.97,NaN,42.9,2,False,ananya.garcia@corp.com,False,11.405886,2015.0,4.0
147,E1130,Rohan Sharma,36.0,engineering,melbourne,2018-03-15,11,140993.15,5838.91,3.5,41.3,2,False,rohan.sharma@corp.com,False,8.481862,2018.0,3.0
162,E1130,Rohan Sharma,36.0,engineering,melbourne,2018-03-15,11,NaN,5838.91,NaN,41.3,2,False,rohan.sharma@corp.com,False,8.481862,2018.0,3.0
17,E1162,Rohan Sharma,30.0,None,perth,NaT,5,NaN,2375.63,NaN,33.2,3,False,rohan.sharma@corp.com,False,NaN,NaN,NaN
108,E1162,Rohan Sharma,30.0,None,perth,NaT,5,59947.80,2375.63,3.9,33.2,3,False,rohan.sharma@corp.com,False,NaN,NaN,NaN
74,E1199,Sneha Tanaka,42.0,hr,bangalore,2020-06-16,15,NaN,2960.25,NaN,NaN,2,True,sneha.tanaka@corp.com,False,6.225873,2020.0,6.0
125,E1199,Sneha Tanaka,42.0,hr,bangalore,2020-06-16,15,101090.15,2960.25,3.5,NaN,2,True,sneha.tanaka@corp.com,False,6.225873,2020.0,6.0

In [71]:
df["nulls"] = df.isna().sum(axis=1)
df = df.sort_values("nulls")
df = df.drop_duplicates(subset="emp_id", keep="first")
df = df.drop(columns="nulls")

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 175 to 68
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   emp_id                200 non-null    object
 1   name                  200 non-null    object
 2   age                   181 non-null    float64
 3   department            188 non-null    object
 4   city                  190 non-null    object
 5   date_of_joining       191 non-null    datetime64[ns]
 6   experience_years      200 non-null    int64
 7   salary                175 non-null    float64
 8   bonus                 182 non-null    float64
 9   performance score     186 non-null    float64
 10  Work Hours per Week   190 non-null    float64
 11  Projects Completed    200 non-null    int64
 12  remote                200 non-null    bool
 13  email                 200 non-null    object
 14  has_left              200 non-null    bool
 15  tenure_years          191 non-null    float64
 16  joining_year          191 non-null    float64
 17  joining_month         191 non-null    float64
dtypes: bool(2), datetime64[ns](1), float64(8), int64(2), object(5)
memory usage: 27.0+ KB

In [75]:
df.shape

(200, 18)

In [76]:
df["emp_id"].duplicated().sum()

np.int64(0)

In [77]:
df[df["emp_id"] == "E1055"]

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,has_left,tenure_years,joining_year,joining_month
193,E1055,Olivia Singh,48.0,engineering,melbourne,2022-12-25,22,NaN,8268.73,3.6,39.8,3,True,olivia.singh@corp.com,False,3.701574,2022.0,12.0

In [79]:
df.isna().sum()

emp_id                   0
name                     0
age                     19
department              12
city                    10
date_of_joining          9
experience_years         0
salary                  25
bonus                   18
performance score       14
Work Hours per Week     10
Projects Completed       0
remote                   0
email                    0
has_left                 0
tenure_years             9
joining_year             9
joining_month            9
dtype: int64

In [80]:
df["age"] = df["age"].fillna(df["age"].median())

In [81]:
df.isna().sum()

emp_id                   0
name                     0
age                      0
department              12
city                    10
date_of_joining          9
experience_years         0
salary                  25
bonus                   18
performance score       14
Work Hours per Week     10
Projects Completed       0
remote                   0
email                    0
has_left                 0
tenure_years             9
joining_year             9
joining_month            9
dtype: int64

In [82]:
df["salary"] = df["salary"].fillna(df.groupby("department")["salary"].transform("median"))

In [84]:
df["salary"].isna().sum()

np.int64(0)

In [85]:
df.groupby("department")["salary"].median()

department
engineering    109908.665
finance        107886.765
hr              75294.230
marketing       76933.520
sales           95092.550
support         74024.890
Name: salary, dtype: float64

In [100]:
import pandas as pd

df2 = pd.read_csv('messy_employees.csv')

In [101]:
df2.shape

(218, 15)

In [102]:
df2.columns

Index(['emp_id', 'name', 'age', 'department', 'city', 'date_of_joining',
       'experience_years', 'salary', 'bonus', 'performance score',
       'Work Hours per Week ', 'Projects Completed', 'remote', 'email',
       'exit_date'],
      dtype='object')

In [105]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218 entries, 0 to 217
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   emp_id                218 non-null    object
 1   name                  218 non-null    object
 2   age                   202 non-null    float64
 3   department            218 non-null    object
 4   city                  207 non-null    object
 5   date_of_joining       218 non-null    object
 6   experience_years      218 non-null    int64
 7   salary                190 non-null    object
 8   bonus                 199 non-null    float64
 9   performance score     197 non-null    float64
 10  Work Hours per Week   205 non-null    float64
 11  Projects Completed    218 non-null    int64
 12  remote                218 non-null    object
 13  email                 218 non-null    object
 14  exit_date             7 non-null      object
dtypes: float64(4), int64(2), object(9)
memory usage: 25.7+ KB

In [106]:
df2.describe

KeyError: ';,'

In [99]:
df2['age']

KeyError: ';,'