In [1]:
%pip install numpy
%pip install pandas

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import numpy as np

## create arrays using numpy
## create a 1d array


arr1 = np.array([1,2,3,4,5])
print(arr1)

print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)

In [5]:
arr2 = np.array([1,2,3,4,5])

## 2d array

## 1 row , 5 column
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
## 2d array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
### identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
## numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## element wise addition

print("Addition  : ",arr1 + arr2)


## element wise subtraction

print("Addition  : ",arr1 - arr2)

## element wise division

print("Addition  : ",arr1 / arr2)

## element wise multiplication

print("Addition  : ",arr1 * arr2)

Addition  :  [11 22 33 44 55]
Addition  :  [ -9 -18 -27 -36 -45]
Addition  :  [0.1 0.1 0.1 0.1 0.1]
Addition  :  [ 10  40  90 160 250]

In [22]:
arr = np.array([2 , 3 , 4 , 5, 6])

## sq root

print(np.sqrt(arr))


## exponentional

print(np.exp(arr))

## sine
print(np.sin(arr))


## natural log

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]

In [30]:
## slicing and indexig

arr = np.array([[1, 2 , 3 , 4],[5,6,7,8],[9,10,11,12]])
print("Array : " , arr)


print(arr[0][2])


## first row condition , second column condition 
print(arr[1:,2:])

Array :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]

In [34]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]

In [36]:
print(arr[1][1:3])

[6 7]

In [37]:
## modify array elemenrs

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

In [39]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]

In [46]:
### logical operation

data = np.array([1,2,3,4,5,6,7,8])

data[(data > 5) & (data <= 8)]

array([6, 7, 8])

In [5]:
# series

## 1d dimensional array like object

import pandas as pd

data = [1,2,3,4,5]
series = pd.Series(data)
print("Series : \n",series)
print(type(series))

Series :
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
## series from dictionary

data = {'a' : 1 , 'b' : 2}
data_series = pd.Series(data)

print(data_series)

a    1
b    2
dtype: int64

In [7]:
data = [10,20,30]
index = ['a','b','c']

pd.Series(data,index = index)

a    10
b    20
c    30
dtype: int64

In [4]:
## dataframe
## create a  dataframe from a dicitionary of list
import pandas as pd

data = {
    'Name' : ['Krish','John','Jack'],
    'Age' : [25,30,45],
    'City' : ['Bangalore','New york','Flroida']
}

df = pd.DataFrame(data)
print(df)

print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New york
2   Jack   45    Flroida
<class 'pandas.core.frame.DataFrame'>

In [5]:
import numpy as np

np.array(df)

array([['Krish', 25, 'Bangalore'],
       ['John', 30, 'New york'],
       ['Jack', 45, 'Flroida']], dtype=object)

In [12]:
## create a dataframe from list of dictionaruies

data = [
    {'Name' : 'Krish','Age' : 34 , 'City' : 'Bangalore'},
    {'Name' : 'Anukrit','Age' : 22 , 'City' : 'Sydney'},
    {'Name' : 'Aditya','Age' : 22 , 'City' : 'Chennai'}
]


df1 = pd.DataFrame(data)
print(df1)

      Name  Age       City
0    Krish   34  Bangalore
1  Anukrit   22     Sydney
2   Aditya   22    Chennai

In [9]:
df = pd.read_csv('dataframe_practice_130_rows.csv')
df.head()

print(df.tail())

    Employee_ID        Name  Age       City   Department Education  \
125        E126  Person_126   48  Melbourne  Engineering       PhD
126        E127  Person_127   56  Melbourne  Engineering    Master
127        E128  Person_128   49     Hobart  Engineering       PhD
128        E129  Person_129   60     Sydney        Sales   Diploma
129        E130  Person_130   40   Brisbane  Engineering       PhD

    Employment_Type  Experience_Years  Annual_Salary   Join_Date  Product  \
125       Full-time                 4         136235  2026-07-14   Tablet
126       Part-time                13         114176  2026-01-29    Phone
127       Full-time                17         123215  2026-01-05   Tablet
128       Part-time                16          56221  2026-04-03   Laptop
129          Casual                 2         148352  2026-03-30  Monitor

        Category  Quantity  Unit_Price  Total_Sales Order_Status  \
125       Mobile         4          71          284      Pending
126    Computing         2        1283         2566     Returned
127  Accessories         2        1243         2486     Returned
128  Electronics         4        1975         7900    Cancelled
129  Electronics         5        1411         7055    Cancelled

     Performance_Score
125               77.4
126               53.1
127               59.4
128               87.4
129               90.7

In [11]:
### accessing data from data frame

data

[{'Name': 'Krish', 'Age': 34, 'City': 'Bangalore'},
 {'Name': 'Anukrit', 'Age': 22, 'City': 'Sydney'},
 {'Name': 'Aditya', 'Age': 22, 'City': 'Chennai'}]

In [13]:
df1

      Name  Age       City
0    Krish   34  Bangalore
1  Anukrit   22     Sydney
2   Aditya   22    Chennai

In [15]:
type(df1['Name'])

pandas.core.series.Series

In [18]:
df1.loc[0]

Name        Krish
Age            34
City    Bangalore
Name: 0, dtype: object

In [20]:
df1.iloc[0]

Name        Krish
Age            34
City    Bangalore
Name: 0, dtype: object

In [25]:
### accesing a specified element

df1['Name']

df1.at[2,'Age']

df1.at[2,'Name']

'Aditya'

In [26]:
### accesing a secified eement using i at

df1.iat[2,2]

'Chennai'

In [27]:
### data mainipulation with data frames

df1

      Name  Age       City
0    Krish   34  Bangalore
1  Anukrit   22     Sydney
2   Aditya   22    Chennai

In [29]:
## adding a columns
df1['Salary'] = [10000,20000,20000]
print(df1)

      Name  Age       City  Salary
0    Krish   34  Bangalore   10000
1  Anukrit   22     Sydney   20000
2   Aditya   22    Chennai   20000

In [33]:
df1.drop('Salary',axis= 1 ,inplace = True)

print(df1)

KeyError: "['Salary'] not found in axis"

In [36]:
df1['Age'] = df1['Age'] + 1

print(df1['Age'])

0    36
1    24
2    24
Name: Age, dtype: int64

In [39]:
df.drop(0,inplace = True)

print(df.head())

KeyError: '[0] not found in axis'

In [40]:
df.describe()

,Age,Experience_Years,Annual_Salary,Quantity,Unit_Price,Total_Sales,Performance_Score
count,129.000000,129.000000,129.000000,129.000000,129.000000,129.000000,129.000000
mean,40.023256,8.837209,100640.178295,2.953488,1384.899225,4269.255814,75.730233
std,12.534618,5.620541,27895.519314,1.451618,707.059335,3399.129223,14.685205
min,18.000000,0.000000,45800.000000,1.000000,71.000000,88.000000,50.100000
25%,29.000000,4.000000,82938.000000,2.000000,702.000000,1812.000000,63.600000
50%,40.000000,9.000000,101207.000000,3.000000,1355.000000,3025.000000,76.200000
75%,51.000000,13.000000,124254.000000,4.000000,2040.000000,7017.000000,87.400000
max,60.000000,20.000000,148891.000000,5.000000,2491.000000,12455.000000,100.000000

In [41]:
import pandas as pd

In [45]:
df = pd.read_csv('dataframe_practice_130_rows.csv')
df.head()

## df.head(x) print first x rows of the file default(x) = 5

,Employee_ID,Name,Age,City,Department,Education,Employment_Type,Experience_Years,Annual_Salary,Join_Date,Product,Category,Quantity,Unit_Price,Total_Sales,Order_Status,Performance_Score
0,E001,Person_001,58,Melbourne,Sales,Bachelor,Casual,0,59592,2026-07-09,Keyboard,Accessories,2,621,1242,Returned,51.6
1,E002,Person_002,23,Hobart,Data Science,Diploma,Casual,5,73657,2026-05-10,Headphones,Electronics,5,864,4320,Cancelled,90.5
2,E003,Person_003,18,Perth,IT,PhD,Full-time,0,144458,2026-06-28,Mouse,Computing,3,686,2058,Completed,69.0
3,E004,Person_004,40,Melbourne,Finance,Bachelor,Casual,19,90082,2026-03-09,Phone,Electronics,4,2246,8984,Cancelled,91.5
4,E005,Person_005,57,Adelaide,Engineering,Master,Full-time,18,92400,2026-02-19,Tablet,Electronics,1,983,983,Returned,63.9

In [47]:
df.tail()

## df.tail(x) print last x rows of the file default(x) = 5

,Employee_ID,Name,Age,City,Department,Education,Employment_Type,Experience_Years,Annual_Salary,Join_Date,Product,Category,Quantity,Unit_Price,Total_Sales,Order_Status,Performance_Score
125,E126,Person_126,48,Melbourne,Engineering,PhD,Full-time,4,136235,2026-07-14,Tablet,Mobile,4,71,284,Pending,77.4
126,E127,Person_127,56,Melbourne,Engineering,Master,Part-time,13,114176,2026-01-29,Phone,Computing,2,1283,2566,Returned,53.1
127,E128,Person_128,49,Hobart,Engineering,PhD,Full-time,17,123215,2026-01-05,Tablet,Accessories,2,1243,2486,Returned,59.4
128,E129,Person_129,60,Sydney,Sales,Diploma,Part-time,16,56221,2026-04-03,Laptop,Electronics,4,1975,7900,Cancelled,87.4
129,E130,Person_130,40,Brisbane,Engineering,PhD,Casual,2,148352,2026-03-30,Monitor,Electronics,5,1411,7055,Cancelled,90.7

In [48]:
df.describe()

,Age,Experience_Years,Annual_Salary,Quantity,Unit_Price,Total_Sales,Performance_Score
count,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000
mean,40.161538,8.769231,100324.423077,2.946154,1379.023077,4245.969231,75.544615
std,12.585093,5.652109,28019.438364,1.448397,707.492926,3396.322630,14.780477
min,18.000000,0.000000,45800.000000,1.000000,71.000000,88.000000,50.100000
25%,29.000000,4.000000,81866.250000,2.000000,697.500000,1752.000000,63.525000
50%,40.500000,8.500000,100891.500000,3.000000,1354.000000,2964.500000,76.000000
75%,51.000000,13.000000,123994.250000,4.000000,2038.250000,6982.750000,87.325000
max,60.000000,20.000000,148891.000000,5.000000,2491.000000,12455.000000,100.000000

In [49]:
df.dtypes

Employee_ID           object
Name                  object
Age                    int64
City                  object
Department            object
Education             object
Employment_Type       object
Experience_Years       int64
Annual_Salary          int64
Join_Date             object
Product               object
Category              object
Quantity               int64
Unit_Price             int64
Total_Sales            int64
Order_Status          object
Performance_Score    float64
dtype: object

In [55]:
### handling missing values
#shows if something has any missing value
df.isnull().any(axis = 0)

Employee_ID          False
Name                 False
Age                  False
City                 False
Department           False
Education            False
Employment_Type      False
Experience_Years     False
Annual_Salary        False
Join_Date            False
Product              False
Category             False
Quantity             False
Unit_Price           False
Total_Sales          False
Order_Status         False
Performance_Score    False
dtype: bool

In [53]:
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  0
City                 0
Department           0
Education            0
Employment_Type      0
Experience_Years     0
Annual_Salary        0
Join_Date            0
Product              0
Category             0
Quantity             0
Unit_Price           0
Total_Sales          0
Order_Status         0
Performance_Score    0
dtype: int64

In [56]:
df.fillna(0)

,Employee_ID,Name,Age,City,Department,Education,Employment_Type,Experience_Years,Annual_Salary,Join_Date,Product,Category,Quantity,Unit_Price,Total_Sales,Order_Status,Performance_Score
0,E001,Person_001,58,Melbourne,Sales,Bachelor,Casual,0,59592,2026-07-09,Keyboard,Accessories,2,621,1242,Returned,51.6
1,E002,Person_002,23,Hobart,Data Science,Diploma,Casual,5,73657,2026-05-10,Headphones,Electronics,5,864,4320,Cancelled,90.5
2,E003,Person_003,18,Perth,IT,PhD,Full-time,0,144458,2026-06-28,Mouse,Computing,3,686,2058,Completed,69.0
3,E004,Person_004,40,Melbourne,Finance,Bachelor,Casual,19,90082,2026-03-09,Phone,Electronics,4,2246,8984,Cancelled,91.5
4,E005,Person_005,57,Adelaide,Engineering,Master,Full-time,18,92400,2026-02-19,Tablet,Electronics,1,983,983,Returned,63.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,E126,Person_126,48,Melbourne,Engineering,PhD,Full-time,4,136235,2026-07-14,Tablet,Mobile,4,71,284,Pending,77.4
126,E127,Person_127,56,Melbourne,Engineering,Master,Part-time,13,114176,2026-01-29,Phone,Computing,2,1283,2566,Returned,53.1
127,E128,Person_128,49,Hobart,Engineering,PhD,Full-time,17,123215,2026-01-05,Tablet,Accessories,2,1243,2486,Returned,59.4
128,E129,Person_129,60,Sydney,Sales,Diploma,Part-time,16,56221,2026-04-03,Laptop,Electronics,4,1975,7900,Cancelled,87.4
129,E130,Person_130,40,Brisbane,Engineering,PhD,Casual,2,148352,2026-03-30,Monitor,Electronics,5,1411,7055,Cancelled,90.7

In [57]:
df = pd.read_csv('messy_employees.csv')
df.head()

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,exit_date
0,E1139,Rohan Tanaka,33.0,Sales,NaN,06/02/2021,8,96558.7,2723.68,2.9,40.0,2,1,rohan.tanaka@corp.com,NaN
1,E1065,Vikram Chen,32.0,Finance,Melbourne,2021-12-24,5,95487.76,1812.91,2.1,49.2,3,N,vikram.chen@corp.com,NaN
2,E1095,Arjun Ali,24.0,sales,PERTH,2014-05-14,0,NaN,882.69,1.6,36.8,3,No,,NaN
3,E1022,Arjun Jones,27.0,support,Singapore,2023-06-09,0,67002.04,2877.76,3.4,45.7,2,Yes,arjun.jones@corp.com,NaN
4,E1063,Hassan Wong,30.0,Human Resources,Singapore,2011-07-22,0,63310.87,1661.07,2.8,37.0,4,Yes,hassan.wong@corp.com,NaN

In [58]:
df.tail()

,emp_id,name,age,department,city,date_of_joining,experience_years,salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,exit_date
213,E1016,Liam Brown,30.0,HR,Brisbane,2024-11-25,4,72999.99,2982.06,4.3,37.2,3,Yes,liam.brown@corp.com,NaN
214,E1067,Wei Brown,37.0,Sales,PERTH,27-Mar-2016,14,106776.08,4680.69,3.2,41.3,3,Yes,wei.brown@corp.com,NaN
215,E1025,Aarav Jones,30.0,Marketing,NaN,03/05/2020,4,91492.85,3048.72,3.7,47.6,9,1,aarav.jones@corp.com,NaN
216,E1196,Aarav Ali,44.0,Marketing,Singapore,-,24,153627.16,10278.26,4.2,35.9,4,Yes,aarav.ali@corp.com,NaN
217,E1175,Wei Nair,47.0,?,Brisbane,2023-10-24,26,138346.24,5404.73,3.3,0.0,2,No,wei.nair@corp.com,NaN

In [62]:
## shows if any columns name have any missing value
'''df.isnull().any(axis = 0)'''

## shows if any rows name have any missing value
df.isnull().any(axis = 1)

0      True
1      True
2      True
3      True
4      True
       ...
213    True
214    True
215    True
216    True
217    True
Length: 218, dtype: bool

In [63]:
df.dtypes

emp_id                   object
name                     object
age                     float64
department               object
city                     object
date_of_joining          object
experience_years          int64
salary                   object
bonus                   float64
performance score       float64
Work Hours per Week     float64
Projects Completed        int64
remote                   object
email                    object
exit_date                object
dtype: object

In [66]:
df.describe()

,age,experience_years,bonus,performance score,Work Hours per Week,Projects Completed
count,202.000000,218.000000,199.000000,197.000000,205.000000,218.000000
mean,38.881188,8.761468,3867.784824,3.318782,39.045854,3.949541
std,69.753979,12.884742,1738.271058,0.760573,7.482204,1.932555
min,20.000000,0.000000,882.690000,1.300000,-12.000000,0.000000
25%,27.000000,1.000000,2749.880000,2.800000,36.400000,3.000000
50%,32.000000,6.000000,3552.160000,3.300000,39.900000,4.000000
75%,37.000000,12.000000,4700.440000,3.900000,42.900000,5.000000
max,999.000000,99.000000,10860.790000,5.000000,51.400000,9.000000

In [69]:
## fill the missing values with 0
df_copy = df.fillna(0)

print(df_copy.head())

  emp_id             name   age       department       city date_of_joining  \
0  E1139     Rohan Tanaka  33.0            Sales          0      06/02/2021
1  E1065    Vikram Chen    32.0          Finance  Melbourne      2021-12-24
2  E1095      Arjun Ali    24.0            sales      PERTH      2014-05-14
3  E1022      Arjun Jones  27.0          support  Singapore      2023-06-09
4  E1063      Hassan Wong  30.0  Human Resources  Singapore      2011-07-22

   experience_years    salary    bonus  performance score  \
0                 8   96558.7  2723.68                2.9
1                 5  95487.76  1812.91                2.1
2                 0         0   882.69                1.6
3                 0  67002.04  2877.76                3.4
4                 0  63310.87  1661.07                2.8

   Work Hours per Week   Projects Completed remote                  email  \
0                  40.0                   2      1  rohan.tanaka@corp.com
1                  49.2                   3      N   vikram.chen@corp.com
2                  36.8                   3     No
3                  45.7                   2    Yes   arjun.jones@corp.com
4                  37.0                   4    Yes   hassan.wong@corp.com

  exit_date
0         0
1         0
2         0
3         0
4         0

In [70]:
df.isnull().sum()

emp_id                    0
name                      0
age                      16
department                0
city                     11
date_of_joining           0
experience_years          0
salary                   28
bonus                    19
performance score        21
Work Hours per Week      13
Projects Completed        0
remote                    0
email                     0
exit_date               211
dtype: int64

In [78]:
#### filling missing values with the mean of the columns

### this change the values as a copy
df['age'] = df['age'].fillna(df['age'].mean())

/var/folders/8t/z8t0kpz1639_xr5xvw0zqb8h0000gn/T/ipykernel_3242/1134547100.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['age'] = df['age'].fillna(df['age'].mean())

In [80]:
df.isnull().any(axis = 1)

0      True
1      True
2      True
3      True
4      True
       ...
213    True
214    True
215    True
216    True
217    True
Length: 218, dtype: bool

In [84]:
df1 = pd.read_csv('messy_employees.csv')

df1['age'] = df1['age'].fillna(df1['age'].mean())

df1.isnull().sum()

emp_id                    0
name                      0
age                       0
department                0
city                     11
date_of_joining           0
experience_years          0
salary                   28
bonus                    19
performance score        21
Work Hours per Week      13
Projects Completed        0
remote                    0
email                     0
exit_date               211
dtype: int64

In [87]:
df1.dtypes

emp_id                   object
name                     object
age                     float64
department               object
city                     object
date_of_joining          object
experience_years          int64
salary                   object
bonus                   float64
performance score       float64
Work Hours per Week     float64
Projects Completed        int64
remote                   object
email                    object
exit_date                object
dtype: object

In [88]:
### renaming columns

df1.rename(columns = {'salary' : 'Salary'})

,emp_id,name,age,department,city,date_of_joining,experience_years,Salary,bonus,performance score,Work Hours per Week,Projects Completed,remote,email,exit_date
0,E1139,Rohan Tanaka,33.0,Sales,NaN,06/02/2021,8,96558.7,2723.68,2.9,40.0,2,1,rohan.tanaka@corp.com,NaN
1,E1065,Vikram Chen,32.0,Finance,Melbourne,2021-12-24,5,95487.76,1812.91,2.1,49.2,3,N,vikram.chen@corp.com,NaN
2,E1095,Arjun Ali,24.0,sales,PERTH,2014-05-14,0,NaN,882.69,1.6,36.8,3,No,,NaN
3,E1022,Arjun Jones,27.0,support,Singapore,2023-06-09,0,67002.04,2877.76,3.4,45.7,2,Yes,arjun.jones@corp.com,NaN
4,E1063,Hassan Wong,30.0,Human Resources,Singapore,2011-07-22,0,63310.87,1661.07,2.8,37.0,4,Yes,hassan.wong@corp.com,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,E1016,Liam Brown,30.0,HR,Brisbane,2024-11-25,4,72999.99,2982.06,4.3,37.2,3,Yes,liam.brown@corp.com,NaN
214,E1067,Wei Brown,37.0,Sales,PERTH,27-Mar-2016,14,106776.08,4680.69,3.2,41.3,3,Yes,wei.brown@corp.com,NaN
215,E1025,Aarav Jones,30.0,Marketing,NaN,03/05/2020,4,91492.85,3048.72,3.7,47.6,9,1,aarav.jones@corp.com,NaN
216,E1196,Aarav Ali,44.0,Marketing,Singapore,-,24,153627.16,10278.26,4.2,35.9,4,Yes,aarav.ali@corp.com,NaN
217,E1175,Wei Nair,47.0,?,Brisbane,2023-10-24,26,138346.24,5404.73,3.3,0.0,2,No,wei.nair@corp.com,NaN

In [92]:
### change datatypes

df1['age'] = df1['age'].astype('string')

df1.dtypes

emp_id                          object
name                            object
age                     string[python]
department                      object
city                            object
date_of_joining                 object
experience_years                 int64
salary                          object
bonus                          float64
performance score              float64
Work Hours per Week            float64
Projects Completed               int64
remote                          object
email                           object
exit_date                       object
dtype: object